### ISSUE TITLE
Courseware tab takes over a minute to load

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#10]
The Courseware tab in this course takes over a minute to load for user peter2.  I don't know the desired load time for this action but isn't less than a minute? 

https://sandbox2o.mitx.mit.edu/courses/MITx/POC101/3T2014/courseware

**Comment by chrisrossi** [comment]
And just checked in something for that, as well.

**Comment by bdero** [comment]
The recent performance improvement commit (https://github.com/jazkarta/edx-platform/commit/10766ea249f312c6cb0e2cc991d54c2ca44fd9ae) reduced queries by about an order of magnitude:

Before:
SQL queries: 3005 (+2922) - 2.21 seconds

After:
SQL queries: 332 (+249) - .118 seconds

We're down to 9-10 seconds from ~18 seconds of total time per request for the POC102 courseware tab on the sandbox.

**Comment by pdpinch** [comment]
I'm satisfied at this point.
