### ISSUE TITLE
Errors in test_sysadmin related to GIT_REPO_DIR

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#101]
In preparing to rebase on current master I've found there are four failures and one error when running `paver test_system -s lms`.  All of the problems are isolated in `lms.djangoapps.dashboard.tests.test_sysadmin:TestSysadmin`.  Furthermore, all of the tests make use of the [test helper method `_add_edx4edx`](https://github.com/jazkarta/edx-platform/blob/ccx-custom-ids/lms/djangoapps/dashboard/tests/test_sysadmin.py#L71) to load a new course from a github repository.  In all cases the failures arise because the response reports that the repository path provided does not exist.  This text appears in the HTML content of the response, even though the response has a 200 status.

```
Path test_root/course_repos doesn't exist, please create it, or configure a different path with GIT_REPO_DIR
```

I'm pretty certain that this problem is not actually related to ccx, but need to get confirmation from someone on the edx team about it.

@pdpinch, who would be the best person to ask about this issue?

**Comment by pdpinch** [comment]
As it happens, this is probably a question for @carsongee

**Comment by carsongee** [comment]
Does `/edx/var/app/edxapp/course_repos` exist on your box? Or is this happening on jenkins?

**Comment by carsongee** [comment]
Oh, right tests override that value to be `test_root/course_repos` ( https://github.com/edx/edx-platform/blob/master/lms/envs/test.py ), you may want to check permissions there as it seems like it maybe isn't able to create new directories there.

**Comment by cewing** [comment]
I am working on a vagrant box that's quite old, so this permission thing seems the most likely.  I'll hunt and fix 'em and then this should be clear for rebase and a PR.

**Comment by pdpinch** [comment]
These tests appear to be failing on Jenkins too.

**Comment by cewing** [comment]
Fixed.
