### ISSUE TITLE
`OpaqueKeys are immutable` error

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#103]
From https://github.com/edx/edx-platform/pull/8395#issuecomment-110101797 and https://gist.github.com/amir-qayyum-khan/b3ea7a5ac47737fc537c

I was also able to reproduce this in our sandbox when I tried to rerun a old mongo course to get it into split mongo.

**Comment by cewing** [comment]
I pushed a fix for this yesterday @pdpinch.  Please try it again after updating your sandbox to the latest head of the `ccx-custom-keys` branch.

**Comment by pdpinch** [comment]
FYI @pwilkins 

@bdero can you update the sandbox?

**Comment by cewing** [comment]
Any news on what is causing this?  Or if it has been solved by the work done so far?

**Comment by pdpinch** [comment]
confirmed fixed.
