### ISSUE TITLE
CCX: unenrolled students still appear in Student List Management control

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#119]
When I unenroll or revoke access for a user in the CCX Enrollment tab, the user's name remains in the Student List Management control even though the CCX is no longer available in the user's dashboard.

1. As Coach revoke access of a CCX student.
2. Verify that the student's name remains listed as an enrolled student.
3. As the student, verify that the CCX is no longer in your Dashboard.

**Comment by jetej** [comment]
As mentioned in https://github.com/jazkarta/edx-platform/issues/78#issuecomment-122032690.

**Comment by jetej** [comment]
I saw this issue again on today's deploy on sandbox2o.  I attempt to revoke access using "Student List Management" but the student still has access to the CCX and the student is still listed.

**Comment by jetej** [comment]
Today's deploy on sandbox2o fixed a few issues. The CCX coach can now "add students" and "revoke access" using "Student List Management".  Unenrolled students appear in "Student List Management".
https://github.com/edx/edx-platform/pull/8986

**Comment by pdpinch** [comment]
closed via edx#9335
