### ISSUE TITLE
Selecting time in CCX Coach Dashboard

### ISSUE THREAD

**Issue by jetej** [jazkarta/edx-platform#120]
I've noticed that you cannot select the times for 'start date' or 'end date'. Therefore, you cannot properly add content via the 'Schedule' tab in the 'CCX Coach Dashboard'

At the moment, you can only select start and end date/time after you add the content.

This was tested on sandbox2o.

![screen shot 2015-07-28 at 3 35 47 pm](https://cloud.githubusercontent.com/assets/8117756/8942001/1505d9d6-3541-11e5-9aa4-36d98318560e.png)

**Comment by pwilkins** [comment]
This issue https://github.com/jazkarta/edx-platform/issues/64 was previously reported and "fixed".  It worked until the recent accessibility update to date/time widgets.

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you look into this?

**Comment by amir-qayyum-khan** [comment]
yes sure @pdpinch

**Comment by jetej** [comment]
In addition, I found that two overlapping calendars will appear if the user clicks on the black arrow pointing down in the text field for "Start Date" or "Due Date".

Also tested on sandbox2o.

![screen shot 2015-07-29 at 11 29 37 am](https://cloud.githubusercontent.com/assets/8117756/8961850/9496348a-35e5-11e5-938a-94b12e6f0591.png)

**Comment by jetej** [comment]
Possibly related issue regarding the drop down calendar for "Start Date" and "Due Date" https://github.com/jazkarta/edx-platform/issues/121
