### ISSUE TITLE
CCX: Overlapping Calendars in CCX Coach/Schedule

### ISSUE THREAD

**Issue by jetej** [jazkarta/edx-platform#121]
This regards the schedule interface on the CCX Coach Dashboard.

I found that two overlapping calendars will appear if the user clicks on the black arrow pointing down in the text field for "Start Date" or "Due Date".  Both calendars are functional and properly enter selected dates into the text field.

This was tested on sandbox2o.

![screen shot 2015-07-29 at 11 29 37 am](https://cloud.githubusercontent.com/assets/8117756/8961850/9496348a-35e5-11e5-938a-94b12e6f0591.png)

**Comment by amir-qayyum-khan** [comment]
already fixed in https://github.com/edx/edx-platform/pull/9114

**Comment by jetej** [comment]
Issue already exists at https://github.com/jazkarta/edx-platform/issues/63.
