### ISSUE TITLE
CCX coach cannot access the "CCX Coach" tab when viewing the gradebook

### ISSUE THREAD

**Issue by jetej** [jazkarta/edx-platform#123]
Tested on sandbox2o.mitx.mit.edu

I have noticed when the CCX coach navigates to the gradebook using CCX Coach/Student Admin/View gradebook, they cannot easily return to the "CCX Coach" tab.  When the user is at the gradebook page only the "Course Info" tab is visible. If he clicks on "Course Info" it will say that he is not enrolled yet and will provide a link to sign up.  That link leads to a "Page Not Found" error.

The dashboard button is still visible but access to the "CCX Coach" tab may be desired.

![screen shot 2015-08-03 at 11 49 14 am](https://cloud.githubusercontent.com/assets/8117756/9041356/b1ce6a6a-39d5-11e5-8240-501b85f3bafd.png)

![screen shot 2015-08-03 at 11 42 49 am](https://cloud.githubusercontent.com/assets/8117756/9041305/787113d0-39d5-11e5-92ce-09894ad30399.png)

![screen shot 2015-08-03 at 11 43 03 am](https://cloud.githubusercontent.com/assets/8117756/9041306/7af8ec7c-39d5-11e5-8a65-e01c37da5fd4.png)

**Comment by pdpinch** [comment]
I believe this is because the coach isn't enrolled in the CCX by default. @jetej can you confirm that this behavior changes if the coach is enrolled in the CCX by name?

**Comment by jetej** [comment]
Yes, when the CCX coach enrolls himself in his CCX he can see the other tabs.  This may be a bit confusing if the CCX coach tries this because he will see both the CCX and master course in his dashboard.

![screen shot 2015-08-03 at 12 10 39 pm](https://cloud.githubusercontent.com/assets/8117756/9041867/b3f5f260-39d8-11e5-8886-175ad202f6a7.png)

![screen shot 2015-08-03 at 12 08 52 pm](https://cloud.githubusercontent.com/assets/8117756/9041870/b9e518cc-39d8-11e5-9ac3-6086fe6e9863.png)
