### ISSUE TITLE
Streamline production configuration

### ISSUE THREAD

**Issue by bdero** [jazkarta/edx-platform#13]
Original line comment: https://github.com/jazkarta/edx-platform/commit/9c9799fdefaf8b86473b18793b77e032acd5fd0d#diff-a102f3c6918039ccbaed2831b7bd1280L399

Since the configuration for POCs is growing more complex, a block in aws.py that inserts the middleware/override providers when PERSONAL_ONLINE_COURSES is true (similar to how it's done with AUTH_USE_CAS) would be useful.

For example:
```python
if FEATURES.get('PERSONAL_ONLINE_COURSES'):
    INSTALLED_APPS += ('pocs')
    MIDDLEWARE_CLASSES += ('pocs.overrides.PocMiddleware')
    FIELD_OVERRIDE_PROVIDERS += (
        'pocs.overrides.PersonalOnlineCoursesOverrideProvider'
    )
```

It would be even better to chain the effect down to individual student override provider:
```python
if FEATURES.get('PERSONAL_ONLINE_COURSES'):
    INSTALLED_APPS += ('pocs')
    MIDDLEWARE_CLASSES += ('pocs.overrides.PocMiddleware')
    FIELD_OVERRIDE_PROVIDERS += (
        'pocs.overrides.PersonalOnlineCoursesOverrideProvider'
    )
    FEATURES['INDIVIDUAL_DUE_DATES'] = True

if FEATURES.get('INDIVIDUAL_DUE_DATES'):
    FIELD_OVERRIDE_PROVIDERS += (
        'courseware.student_field_overrides.IndividualStudentOverrideProvider'
    )
```

**Comment by chrisrossi** [comment]
Done.
