### ISSUE TITLE
Saving content in Schedule tab returns error

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#14]
Saving content in the Schedule tab returns an error.  The most likely Story to link this to is Story13.
![schedule-save-error](https://cloud.githubusercontent.com/assets/145821/5550437/db7ffe34-8b73-11e4-8b3c-351b95399ad6.png)
The backend error is:
```
IntegrityError: (1062, "Duplicate entry '9-i4x://MITx/4.605x_2/course/3T2014-grading_policy' 
for key 'pocs_pocfieldoverride_poc_id_4f056f5d7ea7a9ca_uniq'")
```

**Comment by pdpinch** [comment]
I believe this has been addressed by changes to input validation. If there are any further issues with setting schedules, they should go into their own, more specific issues.
