### ISSUE TITLE
The same date and time picker should be used in the schedule grid and in the "Schedule a Unit" sidebar. 

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#19]
Ideally, we should use the same date and time picker that edX uses in Studio. However, the one currently in use for the schedule grid is fine and could be used everywhere if it is easier to implement at this point. 

edX Studio picker (best):
![screen shot 2015-01-13 at 7 56 34 pm](https://cloud.githubusercontent.com/assets/430126/5732355/6bd34ec4-9b5e-11e4-9860-7e1080b21e8c.png)

Schedule grid picker (ok):
![screen shot 2015-01-13 at 7 33 42 pm](https://cloud.githubusercontent.com/assets/430126/5732325/152518f0-9b5e-11e4-8f2a-6f9329367aaf.png)

"Schedule a Unit" picker in Firefox (not good):
![screen shot 2015-01-13 at 7 33 59 pm](https://cloud.githubusercontent.com/assets/430126/5732332/237b697c-9b5e-11e4-9f00-44d48f0c0a01.png)

"Schedule a Unit" picker in Chrome (inconsistent):
![screen shot 2015-01-13 at 7 34 37 pm](https://cloud.githubusercontent.com/assets/430126/5732336/3727d9ec-9b5e-11e4-94db-c52b981591e4.png)

**Comment by pwilkins** [comment]
Can I add that it would be a better user experience if the same date picker widget was used in both places on the page where date entry is required?  Same for the time picker widget.

**Comment by cguardia** [comment]
This was fixed as part of the js refactoring merged tonight. The schedule UI now uses the same widgets in both places, though it's not the widget used in studio.

**Comment by pwilkins** [comment]
Between Firefox and Chrome, The widgets are more alike now than they were before.  Between Firefox and Safari the widgets appear the same.  Given the time constraint, this is acceptable for the time being.
