### ISSUE TITLE
There should be a user warning on the Grading Policy tab

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#27]
> WARNING: For advanced users only. Errors in the grading policy can lead to the course failing to display. This form does not check the validity of the policy before saving. 

> Most coaches should not need to make changes to the grading policy.

**Comment by cewing** [comment]
Checked in what I think is a pretty clear warning.  I used system warning styles I found in sass, so hopefully it's appropriate usage.

**Comment by pwilkins** [comment]
The warning is acceptable.
