### ISSUE TITLE
CCX tabs not rendering

### ISSUE THREAD

**Issue by bdero** [jazkarta/edx-platform#35]
PR #34 fixes this issue.

**Comment by pdpinch** [comment]
@cewing or @cguardia can you merge this?

**Comment by cewing** [comment]
I'll do it as soon as I'm in a place with a desk. Apologies

**Comment by cewing** [comment]
thanks for the fix, @bdero, and apologies for the typo

**Comment by cewing** [comment]
merged, @pdpinch.

**Comment by cewing** [comment]
@pdpinch can you review and close this?

**Comment by pdpinch** [comment]
Sorry, I was having sandbox problems. Looks good now.
