### ISSUE TITLE
Can't delete unit in CCX Schedule tab 

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#36]
I'm unable to delete the single unit in this custom course, or alternately, if there is a way to delete it, I don't find it.  (I don't know what the "remove..." buttons are for, but they don't remove the unit.)
![ccx-schedule](https://cloud.githubusercontent.com/assets/145821/6130910/882961f8-b116-11e4-973c-42a42c590c15.png)

**Comment by pdpinch** [comment]
Same as #37, still a problem in e64d45b7053cdb727f2c305462d16c5ada152406

**Comment by cewing** [comment]
I believe that this is now fixed.  Please test and confirm, @pdpinch, @bdero 

Unfortunately, This fix does not appear to solve #37.

**Comment by cewing** [comment]
@pwilkins, @pdpinch, can we get eyes on this and confirm it is fixed by ef3e501?

**Comment by pdpinch** [comment]
Ok. I can remove sections now. 

I'm having a problem with the hide/reveal accordion interface now. If I can confirm, I'll open another issue.
