### ISSUE TITLE
Unit start date can't be changed in CCX schedule

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#37]
In the previous build, I could click on the Start Date to edit it.  The Start Date is no longer clickable.  I couldn't find a way to change it.
![ccx-schedule](https://cloud.githubusercontent.com/assets/145821/6130992/066aea50-b117-11e4-8986-6f2ddafd6cae.png)

**Comment by pdpinch** [comment]
I just wanted to confirm that I'm still seeing this problem in a sandbox based off of e64d45b7053cdb727f2c305462d16c5ada152406

Is there anything we can do to help debug this?

**Comment by cewing** [comment]
I have been assuming it was an issue related to my renaming work.  I've not had time to dig into it, but @cguardia is scheduled to take a look.  @bdero's find above may be the secret sauce.  I'll fix locally and test now.

**Comment by cewing** [comment]
This is also fixed by https://github.com/jazkarta/edx-platform/commit/a78e3ba25c9a9eb989ea43e754ec0a56f4d2d756

**Comment by cewing** [comment]
It'd be great if someone could confirm this is fixed and close it, @pdpinch

**Comment by pdpinch** [comment]
This appears to be working now.
