### ISSUE TITLE
Replace calls to our `_lineage` method with the XBlock-provided method

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#40]
[According to review](https://github.com/edx/edx-platform/pull/6636/files#r24695222) the `_lineage` method in https://github.com/jazkarta/edx-platform/blob/feature-pocs/lms/djangoapps/courseware/field_overrides.py#L197 is not needed anymore since the XBlock mixin in https://github.com/edx/XBlock/blob/master/xblock/mixins.py#L338 has a `get_parent` method that does the same thing.  We should prefer using existing methods rather than duplicating them with our own.

**Comment by cguardia** [comment]
Note that _lineage is not the same as get_parent. It calls its own _get_parent recursively. I could change _lineage to call the mixins.py get_parent instead, but as it is, I think we still will need _lineage.

**Comment by pdpinch** [comment]
@cguardia since this was a request from the reviewer, would you mind commenting there? https://github.com/edx/edx-platform/pull/6636/files#r24695222

Also, when you say 
> It calls its own _get_parent recursively

I'm not sure what you mean by 'it' -- is that _lineage that calls its own _get_parent ?

**Comment by cguardia** [comment]
Removed our _get_parent method from the _lineage code, in favor of the one from edx.

**Comment by pdpinch** [comment]
@pwilkins can you close this after you do regression tests?

**Comment by pwilkins** [comment]
@pdpinch I could use a little context here.  I don't associate _get_parent() with a specific CCX behavior.  What functionality has changed or been fixed?

**Comment by pdpinch** [comment]
It's a refactoring requested by edX, so there shouldn't be a functionality change. 

I'm not sure where this would manifest. Probably around scheduling, i.e., adding units to the schedule and then having them display/not display properly to the CCX student according to date. 

- Peter

**Comment by pdpinch** [comment]
@pwilkins reports no net new issues after testing this version. I'm closing this.
