### ISSUE TITLE
Write javascript tests to cover the refactored schedule editing code

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#42]
This issue is a duplicate of scrumdo story number 32 [currently in the backlog](https://www.scrumdo.com/projects/project/poc7/iteration/108588)

In [this comment](https://github.com/jazkarta/edx-platform/commit/b3eefb2769fafda781cebca57e62b3f5042a23f7#commitcomment-8727537) the refactor was suggested, and tests requested.  The refactor is now complete, and we need to add tests to cover the js written.  This came up during renaming the package, as an error on my part in missing a name resulted in a broken UI that was not caught by test failures.

**Comment by cguardia** [comment]
@bdero now that I have been changing the schedule js, I'd like to finish the tests, but I ran into a problem running them. I sent you an email. I wonder if you have any suggestions? Thanks.

**Comment by pdpinch** [comment]
@bdero did you get a chance to follow up with Carlos about JavaScript tests?

**Comment by cguardia** [comment]
Sorry this took so long, but just pushed the schedule tests to the testjs branch.

**Comment by pdpinch** [comment]
Sorry, I can't find the branch. Can you post the URL?

If you think it's ready for us to review, I believe the best thing to do is submit a WIP PR to edX, and tag @bdero, @carsongee and @pdpinch

**Comment by cguardia** [comment]
My bad, forgot to mention that the work was done in the jazkarta repository: https://github.com/jazkarta/edx-platform/tree/testjs

It's working and covers most of the code, though there are minor things that are not tested.

**Comment by cguardia** [comment]
Is  there a way to measure coverge of js tests? @bdero?

**Comment by bdero** [comment]
I haven't looked at javascript coverage reports in edx-platform, but grepping for jscover reveals that it's probably built into their tooling.

```bash
➜  edx-platform git:(bdero/sga-experimental) grep -r jscover ./                                         (bdero/sga-experimental⚡)
./.gitignore:jscover.log
./.gitignore:jscover.log.*
./scripts/run_unit_tests.sh:echo 'Configuring jscover...'
./scripts/run_unit_tests.sh:mkdir -p jscover-dist && wget http://files.edx.org/testeng/JSCover-1.0.2.zip -P jscover-dist && unzipjscover-dist/JSCover-1.0.2.zip -d jscover-dist/ && cp jscover-dist/target/dist/JSCover-all.jar jscover-dist && export JSCOVER_JAR=$PWD/jscover-dist/JSCover-all.jar
./scripts/run_unit_tests.sh:echo 'jscover configured'
```

Is there a jscover-dist directory or jscover.log created after you run the tests?

**Comment by bdero** [comment]
Any reason this is assigned to me?

**Comment by cguardia** [comment]
@bdero sorry, re-assigned to myself.

**Comment by pdpinch** [comment]
@bdero I was hoping you could help with code review.

**Comment by cguardia** [comment]
@pdpinch @bdero a code review would be nice. I believe I have covered the most important functionality, but there are some things that are hard to test, like the date popups, which I skipped for the time being.

The actual date change functions that the popup calls are tested, so I think that's all right. However, if we do need 100% coverage, I would have to work on that a bit more. I was just discussing this with @cewing, and we agreed that I should at least measure the current coverage. We found a document that has some information about this, which I will follow today to get some numbers.

Meanwhile, Cris is going to talk to Sarina about how they prefer the PR to be made, since it appears WIP requests are not something they like.

**Comment by cguardia** [comment]
I added more tests. Getting jscover to run was a bit troublesome, but it works. Coverage is at 70%, but the date modal tests would get that to over 90%. However, I was not able to test that today. Lots of JS in the core is below 100%, though. 

Sarina says it's best for them if we make the PR once it's ready, so it would be very helpful if you can review the code and confirm tests pass for you. I merged our master into the testjs branch, and Cris merged edx master there recently, so we are very close to what they have.

**Comment by pdpinch** [comment]
@bdero

**Comment by bdero** [comment]
I ran the tests and they pass for me. All test coverage increase is a :+1: and I think this looks good for review. Please submit a PR to edX.

**Comment by cguardia** [comment]
@pdpinch, @bdero, I created the PR: https://github.com/edx/edx-platform/pull/8019

**Comment by cguardia** [comment]
@pdpinch updated PR.

**Comment by cguardia** [comment]
@pdpinch this was finally merged tonight.

**Comment by cguardia** [comment]
@pdpinch can we close this now?

**Comment by pdpinch** [comment]
Awesome, thanks! (I missed the notification)
