### ISSUE TITLE
use a custom course key type according to architecture review

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#43]
During review of the [open pull request](https://github.com/edx/edx-platform/pull/6636) by the EdX Architecture Council, it was suggested that rather than treating `ccx` overrides as one-off special versions of courseware items, it would be better to be able to reference them using a customized course id type.  Apparently the infrastructure exists to create custom course ids, such that we could identify the overrides for a ccx by an id that included not only the `course-provider-run` identifiers used by a course, but also include a `ccx` identifier as a path segment.  This would improve the ability of ccx data to be incorporated in analytics and course data dumps and so on.

Investigate the feasibility, mechanisms, and impact of this change and then implement it if the MIT team chooses to follow this path.

**Comment by cewing** [comment]
@pdpinch can I get you folks to weigh in on this?  It was my principle takeaway from the architecture meeting and I'd like to know the MIT teams take on this.

**Comment by pdpinch** [comment]
We'd like to leave this as is for now, as it's not a blocker for MVP. 

It might be useful to know the scope of the work required, but we won't be prioritizing it over the other high priority issues here.

**Comment by pdpinch** [comment]
I believe the following notes from @bdero capture the discussion well:

> The solution that Cale Pennington and Dave Ormsbee proposed was that we separate the identity of CCX instances from their respective MOOCs altogether by identifying CCXs using a CCX-specific opaque key that extends CourseKey. This would make the separation of MOOC and CCX enrollments completely transparent to the platform, unifying the enrollment process. The courses would have entirely separate user pools from MOOCs, but still reference the same content, since the course user persistence is all determined by course key.

> The way this would work is by having each CCX identified by its own unique "CCXCourseKey" (for lack of a better name), that consists of the parent CourseKey (e.g. course-v1:MITx+802x+Fall_2015) with an extra component denoting the CCX (e.g. course-v1:MITx+802x+Fall_2015+5).

> The good thing about this is, the implementation doesn't seem far away from what we have right now. The field overrides and CCX role delegation would remain exactly as they are now. With the addition of the new CourseKey type, the separate enrollment process could be entirely removed, and the (problematic) MOOC/CCX switching menu persisted by session would also be discarded, as the LMS will just see them and treat them as different course instances.

**Comment by pdpinch** [comment]
I've gotten some follow-up details from the edX Engineering team on implementing this. I'm going to paste it all here, but I think each of their bullets calls for a separate issue and (probably) a separate PR:

**Comment by pdpinch** [comment]
Ferdi & I spoke with Dave Ormsbee today about PRs and ordering. He suggests the following:

- [ ] 1st PR: #79 
- [ ] 2nd PR: #77 & #78 
- [ ] 3rd PR: #80

**Comment by pdpinch** [comment]
https://github.com/edx/edx-platform/pull/8260 currently in review

**Comment by cewing** [comment]
edx#8395 has been merged and this is now in place.
