### ISSUE TITLE
Add `field` to the unique index in Field Overrides

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#46]
Also from https://github.com/edx/edx-platform/pull/6636#discussion_r25146116
> This is for data integrity, not for performance. We can get into a situation where slow request processing and multiple browser clicks can cause multiple gunicorn workers to attempt to add the same row twice (this happens a lot on StudentModule). That would cause field override setting to permanently break for that user on that field because every subsequent attempt to call .get()/.get_or_create() on it would fail with a MultipleObjectsReturned error. If the unique constraint is extended to include field, then one of create attempts would throw an IntegrityError, and subsequent .get() attempts would be fine.

**Comment by cguardia** [comment]
Done in https://github.com/jazkarta/edx-platform/commit/b967b127c89e8c5bbf52cd02387a6d64c7c9855f

**Comment by pdpinch** [comment]
@bdero do you think this would address some of the issues that @pwilkins has seen? (like #20 or #24 )

**Comment by bdero** [comment]
@pdpinch I can't tell if this has anything to do with #24 due to the stack trace linked no longer being available. And it would take more investigation to tell if #20 is caused by this I think.
