### ISSUE TITLE
use assertNumQueries() in tests

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#47]
This comes from a concern about performance related to the number of queries for calculating an override. See https://github.com/edx/edx-platform/pull/6636#discussion_r25146861

**Comment by cguardia** [comment]
Added some tests that test number of queries where override field providers are used in test modules.

**Comment by bdero** [comment]
Is this assigned to me for verifying that the tests in b96b04c027b3f1f0716114529ecd9d70ffa5a20d are passing? At a glance, this looks resolved to me.

**Comment by pdpinch** [comment]
Thanks @bdero
