### ISSUE TITLE
2 course key changes from Cale (minor changes)

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#50]
https://github.com/edx/edx-platform/pull/6636#discussion-diff-25367094 This should just be CourseKey.from_string(course_id)

https://github.com/edx/edx-platform/pull/6636#discussion-diff-25367159 s/requested_ccx.course_id.to_deprecated_string()/unicode(requested_ccx.course_id)/

**Comment by cguardia** [comment]
This was done in https://github.com/jazkarta/edx-platform/commit/3fc87dc26773719d2d0f7b60b6515a73f71727d2

**Comment by pdpinch** [comment]
@pwilkins can you close this once you've done regression tests?

**Comment by pdpinch** [comment]
@pwilkins reports no net new issues after testing this version. I'm closing this.
