### ISSUE TITLE
Duplicate CCXs appear in Dashboard

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#51]
I created a new user and added them as student in my CCX.
When I opened the edX Dashboard I found two instances of the CCX, both of which returned a 500 error when I click "view course".

**Comment by cguardia** [comment]
Is that when you opened the dashboard logged in as this new user, or as a coach?

**Comment by pwilkins** [comment]
This is a user is a student with no coach privileges.

**Comment by cguardia** [comment]
I was not able to duplicate this problem. I tried registering new users and then adding them to the ccx, and I also tried adding them before registering. Could you try again and let me know what steps you take?

**Comment by pwilkins** [comment]
I can't reproduce the problem, either.  Here's the screenshot just so I'm not accused of hallucinating.

![dup-ccx](https://cloud.githubusercontent.com/assets/145821/6561412/82eb86ec-c667-11e4-8f90-8bfceb9bef74.png)

**Comment by pdpinch** [comment]
I'm going to wave my hands and say that one of the data integrity checks is preventing this from happening again. 

If it comes back, feel free to re-open the issue. 

- Peter
