### ISSUE TITLE
Add comment to lms/djangoapps/ccx/__init__.py

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#52]
request from Ned at https://github.com/edx/edx-platform/pull/6636/#discussion_r25203981

(I don't know why this link isn't working, it's edx-platform/pull/6636/#discussion_r25203981

**Comment by cguardia** [comment]
This one was already done as part of #49

**Comment by pdpinch** [comment]
Sorry about the dupe.
