### ISSUE TITLE
Add comment to common/lib/xmodule/xmodule/course_module.py 

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#53]
request from Dave Ormsbee: [edx-platform/pull/6636/#discussion-diff-25146288](https://github.com/edx/edx-platform/pull/6636/#discussion-diff-25146288)

**Comment by cguardia** [comment]
Done.

**Comment by pdpinch** [comment]
fixed in https://github.com/jazkarta/edx-platform/commit/d850e9a37e84818fc5efee11b61623fa7048d972 (I believe)
