### ISSUE TITLE
remove unecessary tear-down from tests

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#54]
comment from Ned: [edx-platform/pull/6636/#discussion_r25607237](https://github.com/edx/edx-platform/pull/6636/#discussion_r25607237)

**Comment by cguardia** [comment]
Verified that tests run fine without it and removed.

**Comment by pdpinch** [comment]
fixed in https://github.com/jazkarta/edx-platform/commit/8e85919aba48adb67beb3a8a9183c31a28b93daa
