### ISSUE TITLE
tiny test refactor: assert the list is empty instead of having a length of zero

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#55]
from Ned, regarding [edx-platform/pull/6636/#discussion-diff-25607414R533](https://github.com/edx/edx-platform/pull/6636/#discussion-diff-25607414R533)

> self.assertEqual(memberships, []) is a simpler and better way to test this.

**Comment by cguardia** [comment]
This pattern was used in several places. Now using the recommended way.

**Comment by pdpinch** [comment]
Fixed in https://github.com/jazkarta/edx-platform/commit/f838153f22056137f5ddee390d92477b19e18e2a and https://github.com/jazkarta/edx-platform/commit/30f6de61efda5f0e4ebc16f15a0e1bf039b582a3
