### ISSUE TITLE
DRY in tests?

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#56]
I'm not exactly sure [what Ned's asking for here](https://github.com/edx/edx-platform/pull/6636/#discussion-diff-25607702):

> This function (and iter_blocks below) are also in test_views.py

@cguardia or @cewing can you take a look?

**Comment by cguardia** [comment]
Got rid of duplicate code in tests.

**Comment by pdpinch** [comment]
fixed by https://github.com/jazkarta/edx-platform/commit/9993b91549ff4a866eec71ddb5428efaff17fe50, I believe
