### ISSUE TITLE
Add comment about why start & due are being converted to strings

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#57]
[question from Ned](https://github.com/edx/edx-platform/pull/6636/#discussion_r25613797)

> Why is this conversion here? What does it do?

I'm not sure if a comment is necessary, or if a response to Ned will do.

**Comment by cguardia** [comment]
Added a comment, in case someone else wonders.

**Comment by pdpinch** [comment]
fixed in https://github.com/jazkarta/edx-platform/commit/d850e9a37e84818fc5efee11b61623fa7048d972
