### ISSUE TITLE
Add logging in views.py

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#58]
Two requests from Ned: [edx-platform/pull/6636/#discussion_r25617845](https://github.com/edx/edx-platform/pull/6636/#discussion_r25617845) and [edx-platform/pull/6636/#discussion-diff-25617854](https://github.com/edx/edx-platform/pull/6636/#discussion-diff-25617854)

**Comment by cguardia** [comment]
Added logging in both places.

**Comment by pdpinch** [comment]
fixed in https://github.com/jazkarta/edx-platform/commit/523f90109f2d146208d0ec4e19c6dd568349a4f0
