### ISSUE TITLE
registration email not sent

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#59]
As a coach I add a student to a CCX.  The student (a different user) should get an invitation to register but doesn't.  The student _does_ see the CCX in his Dashboard, but the link in the "not enrolled yet" flash returns a 500 error.  (this may be a second, unrelated error.)

![enroll-here](https://cloud.githubusercontent.com/assets/145821/6559890/650d9b66-c65c-11e4-80cf-23dff2067081.png)

**Comment by pdpinch** [comment]
Which method did you use to add the student? "Batch Enrollment" or "Student List Management" ?

**Comment by pwilkins** [comment]
I can't reproduce this so I'm closing it.
