### ISSUE TITLE
Where did the triangles and Xs go? (schedule tab)

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#60]
I'm not sure when this happened, but we used to have blue disclosure triangles and red x's in the schedule tab. Now we do not. 

From the screencast recorded 1/9:

![screen shot 2015-03-12 at 1 26 38 pm](https://cloud.githubusercontent.com/assets/430126/6624620/d6170052-c8c0-11e4-8626-9717c156af95.png)

From today's code:

![screen shot 2015-03-12 at 2 05 50 pm](https://cloud.githubusercontent.com/assets/430126/6624633/eec50cde-c8c0-11e4-9cc5-25917f7d2ac1.png)

**Comment by cguardia** [comment]
Apparently, we were using bootstrap icons and edx uses font awesome. Switching to those icons fixed the issue.

**Comment by pdpinch** [comment]
@pwilkins I think you saw this working? If I'm wrong, please re-open.

**Comment by pwilkins** [comment]
It's working for me as well.
