### ISSUE TITLE
diff quality test fails

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#61]
Jenkins says we need more quality in 2962957 and bdc6310

see https://build.testeng.edx.org/job/edx-platform-all-tests-pr-flow/1724/Diff_Quality_Report/

**Comment by cguardia** [comment]
This was very time consuming, but it's done. See here:

https://build.testeng.edx.org/job/edx-platform-all-tests-pr-flow/1739/Diff_Quality_Report/

Note that even though the rest of the edx code base is free of pep8 violations, it does have more than 5,000 pylint infractions, so it appears that they don't make a huge emphasis on that. Anyway, we won't be guilty of getting that number up now.

**Comment by pdpinch** [comment]
Thanks @cguardia !
