### ISSUE TITLE
Do we have a dependency on MILESTONES_APP?

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#62]
When we deployed 2e73bada6e8dd6a4e4c614437e90f5204165c46e on our sandbox, courseware everywhere returned a 500 error. We tracked it down to some code related to the MILESTONES_APP feature flag. Setting the flag to true (as it is on edx.org) cleared the error. 

Not clear yet whether this is a general edX issue, or if it is something that needs to be fixed in this branch.

**Comment by pdpinch** [comment]
edX may be working on this already, in https://github.com/edx/edx-platform/pull/7320

**Comment by mattdrayer** [comment]
@pdpinch -- the fix should be ready to merge at this point -- just waiting on Jenkins to give the green light.

**Comment by pdpinch** [comment]
@cewing can you rebase to pick up the fix from edx#7320  ?

Then @bdero can do a deploy with the MILESTONES_APP feature flag.

**Comment by cewing** [comment]
Will do ASAP. Likely 10 am PT

Cris Ewing
************
Cris Ewing Developer, LLC
http://crisewing.com
cris@crisewing.com
@crisewing
206.724.2112

**Comment by cguardia** [comment]
The rebase was done on Friday. The fix should be in.

**Comment by pdpinch** [comment]
@bdero please do a deploy Monday morning.

**Comment by bdero** [comment]
Just deployed this.

**Comment by pdpinch** [comment]
Looking good.
