### ISSUE TITLE
adding a Schedule start date in the right nav is ignored

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#64]
In the Schedule tab right-side nav, I can specify a unit to add and a start date.  When I click add unit, the unit appears in the schedule, but the date is lost.

**Comment by amir-qayyum-arbisoft** [comment]
@pdpinch done with fix

**Comment by amir-qayyum-arbisoft** [comment]
@pdpinch 

*Scenarios testes* 

*Scenarios 1*
1) Open schedule tab on the right selected chapter, sequential and unit
2) added start date only 
3) refresh 
4) noting add
5) add again and  save
6) Can see start date 
7) refresh 
8) Can see the start date 

*Scenarios 2*
1) Open schedule tab on the right selected chapter, sequential and unit
2) added start date and end date
5) add unit and  save
6) Can see start date 
7) refresh 
8) Can see the start date 

In all Scenarios start date is present .

**Comment by pdpinch** [comment]
I'm seeing the same thing. I'm closing this issue.
