### ISSUE TITLE
Schedule content doesn't appear for student

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#65]
When I set content in the Schedule tab, the student sees all course content.  This is similar to #8 though it seemed useful to create it as a new issue.

**Comment by cguardia** [comment]
Still haven't been able to figure out this one. Will keep trying on Monday.

**Comment by pdpinch** [comment]
Are you seeing it as well? I'd like to confirm that it isn't some specific to our sandbox. 

----------------
I am mobile.

**Comment by cguardia** [comment]
Yes, I'm seeing it. After stepping through code, seems like we are overriding 'visible_to_staff_only', but the toc rendering is using only 'hide_from_toc', so the overridden field is never used when displaying  the course navigation. 

Trying to find out if they changed that recently.

**Comment by cguardia** [comment]
Ok, this took a bit to track, but turned out to be a merge problem. Somehow the access check code was duplicated before and after the descriptor binding in module_render. We needed the check to happen later, but the code that sneaked in caused it to happen before the binding, so the overrides never were used.

**Comment by pdpinch** [comment]
That's awesome that you found it!

Is there a commit or a PR that we can test?

Also, it looks like we'll need a rebase afterwards.

**Comment by cguardia** [comment]
The relevant commit is https://github.com/jazkarta/edx-platform/commit/06e967875b045842abc195605e53ecf88cfbac2b

**Comment by pdpinch** [comment]
This is working for me now on our sandbox. @pwilkins can you confirm?

**Comment by pwilkins** [comment]
confirmed.
