### ISSUE TITLE
icon in 'set date' dialog not rendered

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#70]
The icon in the upper right corner of the 'set date' dialog doesn't render and is inactive.

![set-date-icon-missing](https://cloud.githubusercontent.com/assets/145821/6928570/ee436812-d7c2-11e4-99d8-de342a865df2.png)

**Comment by pdpinch** [comment]
@pwilkins can you validate this when edX releases it?

**Comment by pwilkins** [comment]
Yes, certainly.

**Comment by pdpinch** [comment]
Well, we can't validate this on edge.edx.org at the moment.
