### ISSUE TITLE
CCX Courses that aren't yet released are clickable in student dashboard

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#75]
And if the CCX student clicks on the course, they won't be able to see it even if an override has been set. 

This is also open edX [JIRA #2009](https://openedx.atlassian.net/browse/TNL-2009)

If it makes sense, a fix to this issue could be combined with #74

**Comment by cewing** [comment]
@pdpinch, @bdero, could you help me understand what exactly constitutes an "unreleased" course (or CCX)?  I'm thinking it has to do with the start date for the course, but am not sure.  Any information you can provide that would help me calculate whether a CCX is released or not would be helpful.

Thanks

**Comment by cewing** [comment]
@pdpinch, @bdero, to be clear, at the moment the only arbiter of whether a CCX has "started" or "ended" is whether the course from which it was made has started or ended.  There is no way that I am aware of to set a different "start" or "end" for a CCX.  

I could leverage the schedule for the course, and look for the earliest start and latest end date for scheduled units within the CCX, but that seems quite expensive and I'm not sure it's actually what is wanted.

**Comment by pwilkins** [comment]
@cewing @pdpinch @bdero Coaches expect that setting the start date of the CCX controls when students are able to see the CCX.

**Comment by pwilkins** [comment]
@cewing @pdpinch Link to story#13 https://www.scrumdo.com/projects/story_permalink/787273

**Comment by cewing** [comment]
Shoot.  I apologize @pwilkins.  I must have missed seeing that in the UI.  I'll look again more carefully and close this out.

**Comment by cewing** [comment]
With the changes committed in 361670d this should now be fixed.  If a CCX has a start date which has not yet arrived, the display of the ccx on the student dashboard will not provide any clickable links and will show the upcoming start date.

**Comment by pdpinch** [comment]
@bdero has the sandbox been updated to include 99fbc89 ?

**Comment by pdpinch** [comment]
@pwilkins can you test this (on edge and/or sandbox2o) and close if appropriate?

**Comment by pwilkins** [comment]
I have verified that this is now works properly.  The CCX appears in the student dashboard but it can't be opened and its start date reflects the CCX schedule setting.
