### ISSUE TITLE
Race condition while creating CCX can cause perma 500

### ISSUE THREAD

**Issue by carsongee** [jazkarta/edx-platform#81]
Currently the creation of a CCX is not in a transaction, so race conditions are possible. This happened to me in the "wild" on edx.org, and I'm now no longer able to do anything with that course as I'm getting MultipleObjectsReturned: get() returned more than one CustomCourseForEdX -- it returned 2!. I believe the correction needs to be added around https://github.com/edx/edx-platform/blob/master/lms/djangoapps/ccx/views.py#L124-L129. I have the full stack trace if needed.

**Comment by cewing** [comment]
@carsongee I'd love to see the full stack trace, but I am also wondering if the work I am starting to do this week on fixing issue #43 and the other issues related to it might make this problem obsolete.  How urgent is a fix for this under our current strategy for creating a CCX?

**Comment by carsongee** [comment]
I sent you the trace via e-mail.  I'm not all sure what is involved in changing to a new course key, but if you are no longer using SQL to store CCX names, this would become irrelevant in mysql.

**Comment by cewing** [comment]
Thanks, @carsongee :+1:!  I'll link the [stacktrace](https://gist.github.com/feanil/39330b3bd95385daf512) here for a more persistent and cross-developer reference.

**Comment by cewing** [comment]
We will fix this by ensuring that only one ccx is returned.  

Following discussion with @pdpinch we will mark this fix so that we can eventually allow more than one CCX per coach per course.

**Comment by cewing** [comment]
This is also now fixed.  In the few remaining places where we look up ccx by course and coach rather than by primary key we now get *all* ccxs that match course and coach and return the first one. 

I've left a marker in the `lms.djangoapps.ccx.views` module to mark the location where this could be fixed in the future.
