### ISSUE TITLE
CCX Student should see CCX name on courseware pages

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#82]
This appears to be a regression on edge.edx.org. I haven't tested it anywhere else yet. 

In the upper-left corner of the courseware page, where the course name usually appears, the student should see the name of the CCX instead of the name of the course. 

If we fix this (again) we should add some acceptance tests to avoid future regressions.

**Comment by cewing** [comment]
@pdpinch I agree on the tests idea.  I'll get to work on this.

**Comment by cewing** [comment]
Oh, and once the changes from https://github.com/edx/edx-platform/pull/7771 have been deployed, can we get verification that this issue is not isolated to edge?

**Comment by pdpinch** [comment]
Hmmm. The plot thickens. I can't reproduce this error on our sandbox, even with edx#7771

MOOC title:

![screen shot 2015-04-30 at 10 56 32 pm](https://cloud.githubusercontent.com/assets/430126/7426125/785731e2-ef8c-11e4-8dfa-b2f19f6b3a8a.png)

Same course, as a CCX:

![screen shot 2015-04-30 at 10 55 29 pm](https://cloud.githubusercontent.com/assets/430126/7426130/875ba362-ef8c-11e4-9fec-c04b66a2eb8c.png)

**Comment by jetej** [comment]
@pdpinch This ticket seems to have been resolved. Tested on https://edge.edx.org.

Master course:
![screen shot 2015-08-13 at 10 55 38 am](https://cloud.githubusercontent.com/assets/8117756/9253102/09b72e70-41aa-11e5-83db-55f378867029.png)

CCX:
![screen shot 2015-08-13 at 10 55 49 am](https://cloud.githubusercontent.com/assets/8117756/9253119/24b6a11a-41aa-11e5-895e-4370680c8612.png)
