### ISSUE TITLE
Coach added by Instructor isn't enrolled in course

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#83]
I experienced this on edge.edx.  As an instructor I added a coach.  I logged in as the coach and received a page saying that I was not enrolled in any course.  I will test this in our sandbox as well and report back.

**Comment by pdpinch** [comment]
I'm seeing this on edge as well, and I wonder if we overlooked it on the sandbox because we have admin privileges. It may best to consider this a feature request and in the meantime suggest that coaches register for the course.

**Comment by pwilkins** [comment]
I've learned that this isn't an issue, but a feature.  Course staff needs to be enrolled in a course.  I had mistakenly thought that enrollment was only for students.

**Comment by jetej** [comment]
I've noticed that once the CCX Coach has the CCX set up and with a student enrolled, he can unenroll himself from the master course on which the CCX was based.  This didn't seem to affect much of the Coach account capabilities with the CCX.  I was still able to modify the "Schedule" in the "CCX Coach Dashboard" and see the changes through a student account.  As expected, the Coach no longer had access to the course so I used a direct URL to the "CCX Coach Dashboard".

**Comment by jetej** [comment]
By the way, the above was tested on sandbox2o.mitx.mit.edu

**Comment by jetej** [comment]
This may no longer be relevant because due to https://github.com/jazkarta/edx-platform/issues/78 the student no longer sees both the CCX and the master course in his/her "Dashboard"

**Comment by jetej** [comment]
@pdpinch I believe this ticket can be closed now.

**Comment by pdpinch** [comment]
Closed via edx#9986
