### ISSUE TITLE
Update all coach dashboard views

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#89]
When the coach_dashboard decorator is updated, fix the all coach dashboard views appropriately.

- [x] Update all function signatures to accept a keyword arg for `ccx` which defaults to None
- [x] Update all python code url reversing to use the CCXLocator for the current ccx instead of the course_id of the course.
- [ ] Update all views to raise an exception **or** redirect to an appropriate view if a ccx is required but not passed by the `coach_dashboard` view_decorator.

**Comment by cewing** [comment]
@pdpinch: I am transcribing tasks for ccx id update into issues.

**Comment by cewing** [comment]
In progress, partially completed.

**Comment by cewing** [comment]
The sole remaining issue is viewing/downloading the student gradebook.  There appears to be a problem with doing so when viewing a course with a new-style CourseKey id.  I have sent an email to @cpennington and @dormsbee to seek assistance in resolving that problem.

@pdpinch can you answer this question:

Should viewing a ccx coach dashboard view without having an active CCX raise an error, or redirect to another view (say perhaps the info view for the course provided as part of the view call)

**Comment by pdpinch** [comment]
As discussed a 404 is the appropriate response.

**Comment by cewing** [comment]
This has now been implemented.
