### ISSUE TITLE
Find and fix uses of ccx.overrides.get_current_request

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#91]
If this method is used anywhere, fix it so that it does not rely on the threadlocal `_CCX_CONTEXT`.

If it is not used anywhere, delete the code.

**Comment by cguardia** [comment]
It was used, but there was an existing xmodule method that did the same, so using that now. Code removed (fix in ce3833d69af56aa40b69cd2c68f54de9cee2c46f).

**Comment by cguardia** [comment]
@pdpinch this one is done.
