### ISSUE TITLE
Update enrollment emails (and other emails if any)

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#93]
Everywhere we were using the course_id in an email we should now use the CCXLocator instead.

**Comment by cguardia** [comment]
Fixed by 6a6bf4f1d3389b60fabe7022bef6ec91e5218ddc. @pdpinch this is mostly done, but would like to review with @cewing tomorrow.

**Comment by cewing** [comment]
Enrollment email link is now correct @pdpinch, but student views need fixing (see email) as students are not being seen as registered when they have valid memberships to the CCX
