### ISSUE TITLE
Update page template links

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#94]
Any location in a page template that links to a CCX coach dashboard view should be updated to use the CCXLocator instead of the course_id.

**Comment by cguardia** [comment]
Fixed by 6a6bf4f1d3389b60fabe7022bef6ec91e5218ddc. @pdpinch this is mostly done, but would like to review with @cewing tomorrow.

**Comment by cewing** [comment]
All links are now correct @pdpinch.  some views need repair (gradebook in particular, see email).
