### ISSUE TITLE
Update javascript links for CCX dashboard

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform#95]
Any javascript links or actions that send data to a coach dashboard view should be updated to use the CCXLocator instead of the course_id.

**Comment by cguardia** [comment]
Fixed by 6a6bf4f1d3389b60fabe7022bef6ec91e5218ddc. @pdpinch this is mostly done, but would like to review with @cewing tomorrow.

**Comment by cewing** [comment]
This is done and working.

**Comment by cewing** [comment]
@pdpinch closing this as it is completed.
